### ISSUE TITLE
Oxye Daisy Pure Daisy

### ISSUE THREAD

**Issue by gneumann333** [TheNimbleNinja/Project-Equivalence-Issues#11]
Im a bit confused on how im supposed to get the Oxye Daisy and the pure Daisy.

The default receipe (4 white Petals) does not work and for the receipe in JEI i need a Oxy Daisy to make that i would need a Mana Pool...
Im in an Ocean Biome so no Flower forest.
I cant go to the mining Dimension cause i need Living Rock and Living Wood to make the Portal.

What am i missing?

**Comment by TheNimbleNinja** [comment]
you can get most common resources in your table i bet you havent looked in that

**Comment by gneumann333** [comment]
ooohhh...
![jhd91pC](https://user-images.githubusercontent.com/39131062/86510521-a833f700-bdf0-11ea-819b-3cc3e5d8fb33.jpg)

Thx love the pack!
