### ISSUE TITLE
Thaumcraft Roadblock

### ISSUE THREAD

**Issue by ExecuteOrd66** [TheNimbleNinja/Project-Equivalence-Issues#13]
Crimson Knight unable to spawn naturally in Overworld, due to required structures not spawning. 'The Crimson Cult" research is thus confusing or impossible to obtain, making the 'Void Metal Ingot' (And thus the 'Ultimate Ingot') also unobtainable.

**Comment by TheNimbleNinja** [comment]
fixed by making the crimson knight and cultist spawn eggs craftable
