### ISSUE TITLE
Enchanted fabric crafting leaves spellbinding cloth with 1 durability used

### ISSUE THREAD

**Issue by DH00245** [TheNimbleNinja/Project-Equivalence-Issues#22]
Spellbinding cloth is used in the crafting of enchanted fabric. Spellbinding cloth orginal use was to clean enchantments, and loses durability while doing so. if a spellbinding cloth does not have full durability, the crafting recipe does not work, leading to a lot of space wasted on crafting the enchanted fabric.

Especially considering that the infinity catalyst uses enchanted fabric, you should either make it so one craft uses the whole item, or allow the craft to happen even  if its not at full durability

![image](https://user-images.githubusercontent.com/39643714/101788662-4f088600-3b3b-11eb-80a2-d3aefbba2175.png)

![image](https://user-images.githubusercontent.com/39643714/101789065-c9d1a100-3b3b-11eb-8ff6-85377e305207.png)

**Comment by TheNimbleNinja** [comment]
i couldnt get it to take the whole item

**Comment by TheNimbleNinja** [comment]
i cant fix this as the way to fix it doesnt work in thaumcrafts tables FeelsBadMan
