### ISSUE TITLE
Diamond Drawplate not working in refined storage

### ISSUE THREAD

**Issue by StarBanger69** [TheNimbleNinja/Project-Equivalence-Issues#23]
I am trying to automate the transmission coils, and I can't get the drawplate recipe to work with a not fully repaired drawplate. I even replaced the one in the default recipe with a damaged one, and it didn't take it. 

![2021-01-03_22 11 04](https://user-images.githubusercontent.com/39132142/103497960-1e053380-4e11-11eb-806f-838c979be7c5.png)

![2021-01-03_22 14 34](https://user-images.githubusercontent.com/39132142/103498038-6886b000-4e11-11eb-8e7c-5b6a694c31a4.png)

**Comment by TheNimbleNinja** [comment]
yeah thats on refined storage not liking damaged items thats not something i can fix FeelsBadMan
