### ISSUE TITLE
No way to get Alchemical Coal

### ISSUE THREAD

**Issue by StarBanger69** [TheNimbleNinja/Project-Equivalence-Issues#26]
I'm on the latest version of the pack, and I can't find out how to get Alchemical coal. There are no crafting recipes for it, and it doesn't have an EMC cost.

**Comment by TheNimbleNinja** [comment]
on the very latest version of the pack the quests that tell you to get this have ben removed update your quests with bq_admin default load

**Comment by StarBanger69** [comment]
![2021-02-24_15 05 34](https://user-images.githubusercontent.com/39132142/109059307-1c8a1600-76b2-11eb-9c2b-12180ec65cbf.png)
![2021-02-24_15 05 22](https://user-images.githubusercontent.com/39132142/109059310-1d22ac80-76b2-11eb-98eb-2204d02c19b4.png)
 I used the command, and restarted the game just in case, but it did not fix it.

**Comment by TheNimbleNinja** [comment]
you have to be in cheat mode to use the command

**Comment by TheNimbleNinja** [comment]
and if the quest is still there your not in the recent versions

**Comment by TheNimbleNinja** [comment]
the  recent versions are beta
