### ISSUE TITLE
Thaumcraft Celestial Observation not working

### ISSUE THREAD

**Issue by zeromic** [TheNimbleNinja/Project-Equivalence-Issues#28]
EDIT: Modpack version 4.9 (Expert/Hard) Singleplayer

Only states the Error "Nothing new can be learned from this." when trying to do a Celestial Observertation.

I found the following Infos on Thaumcraft but I dont know if they are related to this modpack:
https://github.com/Azanor/thaumcraft-beta/issues/1450 
(The Users own solution of going over Y128 does not work in this modpack)

https://github.com/Azanor/thaumcraft-beta/issues/801
(The Mod the users found to cause the problem is not in this pack but maybe something similar)

Own findings:
In JourneyMap the Overworld is called "DIM_0" maybe this is related.

(EDIT2: My own workaround was to add an EMC Value to the Notes and use the Transmutation Table)

**Comment by TheNimbleNinja** [comment]
those notes only world in default overworld and im using topography worlds so they wont work sadly
