### ISSUE TITLE
thaumcraft:stone_arcane not craftable (game/progression breaking)

### ISSUE THREAD

**Issue by zeromic** [TheNimbleNinja/Project-Equivalence-Issues#29]
It shows a "%s Vis Crystal" in the Recipe (because its missing some Tag info)

Possible Solution:
Project Equivalence\scripts\all modes\craftweaker\thaumcraft.zs
Line 68:  change "\<thaumcraft:crystal_essence\>" into something like this "\<thaumcraft:crystal_essence\>.withTag({Aspects: [{amount: 1, key: "perditio"}]})"

Note: Had the same problem years ago in another Modpack but never figured out how to get "all" vis crystals to work.

**Comment by TheNimbleNinja** [comment]
that means it accepts all vis crystals
