### ISSUE TITLE
Quite Clear Glass recipe issue

### ISSUE THREAD

**Issue by therodet** [TheNimbleNinja/Project-Equivalence-Issues#30]
There are two problems with the Quite Clear glass recipe:
1) When crafting fused quartz, if the hardened glass is inserted first, the smelter will begin making quite clear glass
2) When auto-crafting with refined storage, Hardened Glass will get put into multiple slots, which causes the smelting to stop working

**Comment by DayDemon67** [comment]
The first problem i would consider more a challenge than an issue but the second would be easily fixable if there were 2 other crafting recipes one for 2 quite clear glass at once and one for 3 (there probably is a fix where you only have the recipe that is in the modpack right now but i am no modder) but until than i reckon speed downgrades should do the trick for now
Attached an image that should explain how you can get over both problems for now tho i would like to see at least the 2nd getting fixed

![QuiteClearGlass](https://user-images.githubusercontent.com/59098289/115200942-71b83600-a0fd-11eb-9f9e-9fe161f78833.png)

**Comment by TheNimbleNinja** [comment]
changed the way there done
