### ISSUE TITLE
Complex Arcane Mechanism recipe

### ISSUE THREAD

**Issue by DayDemon67** [TheNimbleNinja/Project-Equivalence-Issues#31]
This just explains itself.
![Screenshot_1](https://user-images.githubusercontent.com/59098289/115423639-aa900200-a206-11eb-82a6-63afdaf32f47.png)
The recipe is right in the normal arcane workbench version of the recipe but it means that you can't automate it.

**Comment by TheNimbleNinja** [comment]
fixed
