### ISSUE TITLE
Ultimate Stew can't be autocrafted

### ISSUE THREAD

**Issue by therodet** [TheNimbleNinja/Project-Equivalence-Issues#33]
Ultimate Stew can be 99% automated, but when crafting, it leaves behind a Stew Pot in the crafting grid that must be manually removed.
-- Edit --
Same issue with cosmic meatballs and the Liquid Meat bucket

**Comment by TheNimbleNinja** [comment]
you should be able to use the refined avaritia patterns to automate the recipes!

**Comment by therodet** [comment]
Didn't occur to me to try refined avaritia, since they are extended crafting recipes. I'm past those recipes for now, but will give it a try if I decide to go another round in hard mode once I get through normal.
