### ISSUE TITLE
Crafting Recipes Changed

### ISSUE THREAD

**Issue by fairjeremy** [TheNimbleNinja/Project-Equivalence-Issues#34]
Updated from 5.3 to 5.5 and noticed that crafting has been changed.  The main thing I noticed is that coke brick can just be crafted in the most current version, but it also has the recipe for it to be "smelted" in the alloy and induction smelter, I used the Alloy Kiln in the previous version to get coke brick since it was the only way available in that version.  I don't know if it is supposed to be this way, and I know this is still a work in progress.  Just thought I could bring it up if you didn't know about this.

**Comment by TheNimbleNinja** [comment]
your probly in normal mode
