### ISSUE TITLE
Phial duping

### ISSUE THREAD

**Issue by therodet** [TheNimbleNinja/Project-Equivalence-Issues#35]
The newly added Thaumcraft phial duping recipes do not work - they always produce 'Humanus', regardless of source phial. I dove into the Botania code, and it looks like NBT data is ignored when considering the source item to be conjured.
One possible solution would be to introduce a "Conjuration Token"(tm) item that has a few variations for each of the mana costs of existing duplication recipes. The tokens would be dupable using the same amount of mana, and then could be used in a normal crafting grid to duplicate phials, and possibly other items that already have custom conjuration recipes.

**Comment by TheNimbleNinja** [comment]
i sadly removed them in current updates
