### ISSUE TITLE
don't recognize seared gauge

### ISSUE THREAD

**Issue by ghost** [TheNimbleNinja/Project-Equivalence-Issues#36]
Project-Equivalence-5.10
Alloy Smeltery don't recognize seared gauge
What should I do ?

**Comment by ghost** [comment]
one more problem 
Arcane Crafter don't recognize arcane pedestal

**Comment by TheNimbleNinja** [comment]
if your talking about the modular machine alloy smelter there needs to be a specific liquid in the gauges and the pedestals need primordial pearls on them all this is in quests and on the blueprints

**Comment by ghost** [comment]
thank you for your advice. Alloy Smeltery is succeeded.
But Arcane Crafter is not succeeded.
I use blueprint preview and place blocks and put primordial pearls on arcane pedestals.

![スクリーンショット (2)](https://user-images.githubusercontent.com/65548528/118336888-872e4d80-b54d-11eb-8557-bf571f82459b.png)

**Comment by bluelemon101** [comment]
when I try to summon the 3rd Gaia boss for "Extra Botania", I crash immediately
![Screenshot 2021-06-04 144011](https://user-images.githubusercontent.com/85367051/120848428-c6dfc800-c542-11eb-9e7d-97add4eaff3b.png)

**Comment by BjoernAkAManf** [comment]
Hi,

just trying to report my findings i discovered a couple of days ago:
Going to the folder <MC>/config/modularmachinery/machinery/arcane_crafter.json
and replacing "Count": "1b" b< "Count": "1". I got the idea fdrom the arcane_crucible.json file.

Note that i'm currently two versions behind the official version. but this change fixes the crafter for me.

**Comment by TheNimbleNinja** [comment]
changed them to suggested hoping this fixed them :)
