### ISSUE TITLE
Using the rftools spawner with erebus mobs crashes the server

### ISSUE THREAD

**Issue by RMesotten** [TheNimbleNinja/Project-Equivalence-Issues#37]
Found in version 5.9, but checked the rftools.cfg of 5.14 as well. None of the erebus mobs are present in mobspawnamounts or mobspawnrf, which causes a server crash when you insert a syringe into the spawner. Managed to save my world by editing the cfg.

**Comment by TheNimbleNinja** [comment]
okay it seems that rftools spawner is broken as fuck
so ill just remove it T~T
