### ISSUE TITLE
Easy mode missing recipes

### ISSUE THREAD

**Issue by smmailik** [TheNimbleNinja/Project-Equivalence-Issues#39]
In the easy mode some recipes are missing .. 
Thermal..  (the reception coil is not craftable , the redstone servo aswell ) , wooden gears  also .. 
 Latest version of the pack..

**Comment by TheNimbleNinja** [comment]
okay thanks for the info

**Comment by TheNimbleNinja** [comment]
i fixed the ones you metioned thanks for telling me if there was more i didnt see them cause im dumb
