### ISSUE TITLE
Can't craft redstone reception coil on expert

### ISSUE THREAD

**Issue by stels9fox** [TheNimbleNinja/Project-Equivalence-Issues#40]
missing recipes to gold large plate after update to 1.17.5
![image](https://user-images.githubusercontent.com/81447418/124327263-73d45180-db90-11eb-8ff0-a3652260dbf3.png)
![image](https://user-images.githubusercontent.com/81447418/124327283-7df65000-db90-11eb-9f7e-fc5d7d94763b.png)
It would be nice to fix the version numbers too.
![image](https://user-images.githubusercontent.com/81447418/124327623-dd546000-db90-11eb-9658-1d85d82b0e4a.png)

**Comment by stels9fox** [comment]
Okay, the problem is a bit bigger than I originally thought. Gold can no longer be used as a material in tinkers at all.

**Comment by stels9fox** [comment]
I downloaded the modpack again and in the new world the problem with the recipe remained.

**Comment by TheNimbleNinja** [comment]
fixed in new update
