### ISSUE TITLE
FastFurnace's Furnace only smelts one item at a time

### ISSUE THREAD

**Issue by Alsososcar** [TheNimbleNinja/Project-Equivalence-Issues#44]
When i smelt stone or clay, it will only smelt it once and then stop. It starts again when i take the item out of the furnace
V5.17.10

**Comment by choekstr** [comment]
I put a hopper underneath it and once it pulls out the next one starts.  This works until either a fix comes or you can get a dark matter or red matter furnace which shouldn't be that far off from the start with a decent EMC generation (cocoa beans is sooo good)
