### ISSUE TITLE
No quest book 

### ISSUE THREAD

**Issue by sunderMC** [TheNimbleNinja/Project-Equivalence-Issues#45]
I have just started playing and theres only 2 things i spawned with, the materials and you book and the certificate of playing, not sure if this js a bug on my end or not.
![20211006_203059](https://user-images.githubusercontent.com/92056215/136270724-7e6d283a-a1e5-43e2-b5c4-858e896226e5.jpg)

**Comment by TheNimbleNinja** [comment]
the quest book is a keybind that you can change its defalt is grave or ~`
