### ISSUE TITLE
Engineer Hammer Issue

### ISSUE THREAD

**Issue by tallyer** [TheNimbleNinja/Project-Equivalence-Issues#46]
Perhaps I'm missing something, but it now seems impossible to craft an engineer's hammer without needing the engineer's hammer to produce the necessary basic crafting table from extended crafting as the recipe doesn't work on the vanilla crafting table

**Comment by TheNimbleNinja** [comment]
i fixed this in the newest update

**Comment by tallyer** [comment]
Oops. Hadn't realised I wasn't on the most recent version. Thanks for a great mod pack!
