### ISSUE TITLE
Iron bucket is not available

### ISSUE THREAD

**Issue by IWareQ** [TheNimbleNinja/Project-Equivalence-Issues#47]
Using the latest version of the assembly itself, I ran into the problem that it is impossible to create an ordinary iron bucket, because to create plates, you need a stove, but it is impossible to power it with lava

**Comment by TheNimbleNinja** [comment]
did you see the clay bucket?

**Comment by IWareQ** [comment]
> did you see the clay bucket?

Yes, I found. Because is closed
