### ISSUE TITLE
Salis mundus not working on crafting table

### ISSUE THREAD

**Issue by IWareQ** [TheNimbleNinja/Project-Equivalence-Issues#48]
I was able to make a Taumonamicon, but the workbench does not work.

I used 6.3.5 version

**Comment by TheNimbleNinja** [comment]
you have to sleep after obtaining the crystals in order to progress in thaumcraft

**Comment by IWareQ** [comment]
> you have to sleep after obtaining the crystals in order to progress in thaumcraft

I have already slept several times, I got a taumonamicon by clicking on the shelf with salis mundus books, but it does not work with the workbench

**Comment by IWareQ** [comment]
It is possible that this is due to the FastWorkbench mod, because whichever workbench I take, it becomes out of this mod

**Comment by IWareQ** [comment]
https://youtu.be/1gwYnVSon8k 

the video on which the bug is visible
