### ISSUE TITLE
plate crafting quest description is wrong

### ISSUE THREAD

**Issue by DJMeiBear** [TheNimbleNinja/Project-Equivalence-Issues#50]
The description for the quest "Plate Crafting" reads "The first and only plate that can be hand crafted is the iron plate. to craft the others you will have to use either tinkers plate cast or immersive engineering plate press. you can later use the thermal compactor to make plates."

It should read as "the first and only plate that can be hand crafted is the stone plate. to craft the others you will have to use either tinkers plate cast or immersive engineering plate press. you can later use the thermal compactor to make plates."

**Comment by TheNimbleNinja** [comment]
fixed
