### ISSUE TITLE
Can't combine batteries from Integrated Dynamics

### ISSUE THREAD

**Issue by Karyuu-no-Tsume** [TheNimbleNinja/Project-Equivalence-Issues#8]
The batteries seem to be unable to be crafted together to increase storage regardless of what I do. I tried the 2x2 crafting grid, FastWorkbench, the crafting station, every extended crafting table (iron, gold, diamond, emerald), full batteries, empty batteries, batteries placed on the ground then picked up, and batteries from creative. I also tried combining anywhere between 2 and 16 batteries with no avail

**Comment by TheNimbleNinja** [comment]
fixed in dev
